// Generated by https://quicktype.io

export interface Grafica {
  facebook:             number;
  youtube:              number;
  whatsapp:             number;
  "facebook-messenger": number;
  instagram:            number;
}
